
import React from 'react';
import Section from '../shared/Section';
import DocumentTextIcon from '../icons/DocumentTextIcon'; // Example icon

const TermsPage: React.FC = () => {
  // Image by Kelly Sikkema on Unsplash (document/legal concept): https://unsplash.com/photos/3-Tc_5L4q6k
  const pageImageUrl = "https://images.unsplash.com/photo-1583513601401-51540374739b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80";
  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <Section
      title="Terms of Service"
      subtitle="Please read these terms carefully before using Validly."
      animate={true}
      className="bg-brand-gray-900 rounded-xl border border-brand-gray-700 shadow-card"
    >
      <div className="max-w-3xl mx-auto space-y-8 p-2 md:p-4">
        <div className="mb-8 mt-[-1rem] md:mt-0 rounded-lg overflow-hidden border border-brand-gray-700 shadow-md">
          <img 
            src={pageImageUrl} 
            alt="Abstract representation of terms and conditions document" 
            className="object-cover w-full h-48 md:h-64 opacity-80"
          />
        </div>

        <div className="p-6 bg-brand-gray-800 rounded-lg shadow-md border border-brand-gray-700 text-brand-gray-300 leading-relaxed">
          <DocumentTextIcon className="w-10 h-10 text-brand-premium-blue mb-4" />
          <h3 className="text-xl font-semibold text-brand-gray-100 mb-3">Welcome to Validly!</h3>
          <p className="mb-4">
            By accessing or using the Validly application and its services ("Service"), you agree to be bound by these Terms of Service ("Terms"). 
            If you disagree with any part of the terms, then you may not access the Service.
          </p>
          
          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">1. Service Description (Demonstration)</h4>
          <p className="mb-3">
            Validly is an AI-powered tool designed for demonstration purposes. It helps supplement and wellness brands generate science-backed product claims by summarizing relevant public research (simulated) and turning them into marketing assets (simulated). 
            All content, analysis, reports, and data generated by Validly are SIMULATED and for illustrative and educational purposes ONLY.
          </p>

          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">2. No Professional Advice</h4>
          <p className="mb-3">
            The Service does NOT provide medical, legal, regulatory, financial, or any other professional advice. 
            Information provided by Validly, including but not limited to claim validation reports, ingredient analyses, health news, symptom insights, compliance feedback, and formulation ideas, should NOT be relied upon for making any decisions. 
            Always consult with qualified professionals (e.g., doctors, lawyers, regulatory experts, scientists) for specific advice tailored to your situation.
          </p>
          
          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">3. User Responsibilities</h4>
          <p className="mb-3">
            You are responsible for your use of the Service and for any content you provide. You agree not to use the Service for any unlawful purpose or in any way that could harm Validly or third parties.
          </p>

          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">4. Intellectual Property (Placeholder)</h4>
          <p className="mb-3">
            The Service and its original content (excluding user-provided content for analysis), features, and functionality are and will remain the exclusive property of Validly and its licensors.
            [Placeholder for more detailed IP clauses.]
          </p>
          
          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">5. Disclaimers & Limitation of Liability (Placeholder)</h4>
          <p className="mb-3">
            The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Validly makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties.
            In no event shall Validly be liable for any damages arising out of the use or inability to use the materials on Validly's website.
            [Placeholder for more detailed disclaimer and liability clauses.]
          </p>

          <h4 className="text-lg font-semibold text-brand-gray-200 mt-4 mb-2">6. Changes to Terms</h4>
          <p className="mb-3">
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. 
            We will try to provide at least 30 days' notice prior to any new terms taking effect.
          </p>

          <p className="mt-6 text-sm text-brand-gray-400">
            Last Updated: {currentDate}
          </p>
        </div>

        <div className="mt-6 text-sm text-brand-gray-500 text-center">
          <p>If you have any questions about these Terms, please contact us.</p>
        </div>
      </div>
    </Section>
  );
};

export default TermsPage;